name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get SDK Version
      shell: bash
      run: |
        echo "VERSION=$(curl -s https://content.vexrobotics.com/vexos/public/V5/vscode/sdk/cpp/manifest.json |grep latest |grep -o "V5[^\"]*")" >> "$GITHUB_ENV"  
    - name: Download SDK
      uses: wei/curl@master
      with: 
        args: https://content.vexrobotics.com/vexos/public/V5/vscode/sdk/cpp/${{ env.VERSION }}.zip --output sdk.zip
    - name: Unzip SDK
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq sdk.zip     
    - name: Download Toolchain
      uses: wei/curl@master
      with:
        args: https://content.vexrobotics.com/vexos/public/vscode/toolchain/linux/toolchain_linux64.zip --output tools.zip
    - name: Unzip Toolchain
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq tools.zip
    - shell: bash
      run: |
        sudo chmod +x toolchain_linux64/gcc/bin/*
    - run: PATH=${PATH}:toolchain_linux64/gcc/bin make VEX_SDK_PATH=${{ env.VERSION }}
        
