name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get SDK Version
      shell: bash
      run: |
        VERSION=$(curl -s https://content.vexrobotics.com/vexos/public/V5/vscode/sdk/cpp/manifest.json |grep latest |grep -o "V5[^\"]*")  
    - name: Download SDK
      uses: wei/wget@master
      with: 
        args: https://content.vexrobotics.com/vexos/public/V5/vscode/sdk/cpp/${VERSION}.zip
    - name: Unzip SDK
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq ${VERSION}.zip      
    - name: Download Toolchain
      uses: wei/wget@master
      with:
        args: https://content.vexrobotics.com/vexos/public/vscode/toolchain/linux/toolchain_linux64.zip
    - name: Unzip Toolchain
      uses: montudor/action-zip@v1
      with:
        args: unzip -qq toolchain_linux64.zip
        
